[pytest]
pythonpath = .
addopts =
    -v
    --headed
    --browser chromium
    --base-url=https://www.automationexercise.com
    --alluredir=./reports
    --clean-alluredir
testpaths = tests
python_files = test_*.py
markers =
    smoke
